# Generated by Django 5.0.6 on 2026-05-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publisher_remove_book_author_remove_book_genre_and_more'),
        ('loans', '0002_loans_fines_notifications_systemlogs_waitlists_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
