# Generated by Django 5.0.6 on 2026-05-02 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ijarada'), ('returned', 'Qaytarildi'), ('overdue', "Muddati o'tdi")], default='active', max_length=10, verbose_name='Holat')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan vaqt')),
                ('due_date', models.DateField(verbose_name='Qaytarish muddati')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytarilgan vaqt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Ijara',
                'verbose_name_plural': 'Ijaralar',
                'ordering': ['-borrowed_at'],
            },
        ),
    ]
