# Generated by Django 5.0.6 on 2026-05-04 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publisher_remove_book_author_remove_book_genre_and_more'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Qaytarish muddati')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Qaytarilgan sana')),
                ('status', models.CharField(choices=[('borrowed', 'Ijarada'), ('returned', 'Qaytarildi'), ('overdue', "Muddati o'tdi"), ('lost', "Yo'qolgan")], default='borrowed', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcopies', verbose_name='Kitob nusxasi')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loans', to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_loans', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilingan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ijara',
                'verbose_name_plural': 'Ijaralar',
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa')),
                ('reason', models.CharField(choices=[('late_return', 'Kech qaytarish'), ('book_damaged', 'Kitob shikastlangan'), ('book_lost', "Kitob yo'qolgan")], max_length=25, verbose_name='Jarima sababi')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_fines', to=settings.AUTH_USER_MODEL, verbose_name="Kim to'ladi")),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='loans.loans', verbose_name='Ijara')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('due_reminder', 'Muddat eslatmasi'), ('overdue_alert', "Muddati o'tdi"), ('waitlist_ready', "Kitob bo'shadi"), ('fine_issued', 'Jarima yozildi')], max_length=25, verbose_name='Xabar turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Xabar yuborildimi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('book_added', "Kitob qo'shildi"), ('book_deleted', "Kitob o'chirildi"), ('user_blocked', 'Foydalanuvchi bloklandi'), ('fine_added', 'Jarima yozildi'), ('loan_created', 'Ijara yaratildi'), ('loan_returned', 'Kitob qaytarildi')], max_length=25, verbose_name='Amal')),
                ('target', models.IntegerField(blank=True, null=True, verbose_name="Ob'ekt ID")),
                ('target_type', models.CharField(blank=True, choices=[('book', 'Kitob'), ('user', 'Foydalanuvchi'), ('loan', 'Ijara'), ('fine', 'Jarima')], max_length=10, null=True, verbose_name="Ob'ekt turi")),
                ('details', models.TextField(blank=True, null=True, verbose_name='Tafsilotlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Loglar',
            },
        ),
        migrations.CreateModel(
            name='Waitlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('notified', 'Xabardor'), ('fulfilled', 'Bajarildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=25, verbose_name='Holati')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Xabardor qilingan payt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
            },
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
