# Generated by Django 5.0.6 on 2026-05-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loans_fines_notifications_systemlogs_waitlists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='action',
            field=models.CharField(choices=[('book_added', "Kitob qo'shildi"), ('book_deleted', "Kitob o'chirildi"), ('user_blocked', 'Foydalanuvchi bloklandi'), ('fine_added', 'Jarima yozildi'), ('loan_created', 'Ijara yaratildi'), ('loan_returned', 'Kitob qaytarildi'), ('book_updated', 'Kitob yangilandi'), ('author_added', "Muallif qo'shildi"), ('author_updated', 'Muallif yangilandi'), ('author_deleted', "Muallif o'chirildi"), ('publisher_added', "Nashriyot qo'shildi"), ('publisher_updated', 'Nashriyot yangilandi'), ('publisher_deleted', "Nashriyot o'chirildi"), ('category_added', "Kategoriya qo'shildi"), ('category_updated', 'Kategoriya yangilandi'), ('category_deleted', "Kategoriya o'chirildi"), ('book_copy_added', "Kitob nusxasi qo'shildi"), ('book_copy_updated', 'Kitob nusxasi yangilandi'), ('book_copy_deleted', "Kitob nusxasi o'chirildi"), ('fine_paid', "Jarima to'landi"), ('waitlist_created', 'Navbat yaratildi'), ('waitlist_status_changed', "Navbat holati o'zgardi"), ('user_registered', 'Registratsiya'), ('user_unblocked', 'Blokdan yechildi'), ('user_updated', 'Yangilandi')], max_length=25, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='systemlogs',
            name='target_type',
            field=models.CharField(blank=True, choices=[('book', 'Kitob'), ('user', 'Foydalanuvchi'), ('loan', 'Ijara'), ('fine', 'Jarima'), ('author', 'Muallif'), ('publisher', 'Nashriyot'), ('category', 'Kategoriya'), ('book_copy', 'Kitob nusxasi')], max_length=10, null=True, verbose_name="Ob'ekt turi"),
        ),
    ]
