# Generated by Django 5.0.6 on 2026-05-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_systemlogs_action_alter_systemlogs_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fine_amount', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, verbose_name="Kunlik jarima miqdori (so'm)")),
                ('max_loan_days', models.PositiveIntegerField(default=10, verbose_name='Maksimal ijara muddati (kun)')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
    ]
