# Generated by Django 6.0.5 on 2026-05-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_librarysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='requested_days',
            field=models.PositiveIntegerField(default=10, verbose_name="So'ralgan kunlar"),
        ),
        migrations.AlterField(
            model_name='loans',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('borrowed', 'Ijarada'), ('returned', 'Qaytarildi'), ('overdue', "Muddati o'tdi"), ('lost', "Yo'qolgan")], default='pending', max_length=20, verbose_name='Holati'),
        ),
    ]
