# Generated by Django 6.0.5 on 2026-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loans_requested_days_alter_loans_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fines',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jarima', 'verbose_name_plural': 'Jarimalar'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='systemlogs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log', 'verbose_name_plural': 'Loglar'},
        ),
        migrations.AlterField(
            model_name='systemlogs',
            name='action',
            field=models.CharField(choices=[('user_registered', "Foydalanuvchi ro'yxatdan o'tdi"), ('user_updated', 'Foydalanuvchi yangilandi'), ('user_blocked', 'Foydalanuvchi bloklandi'), ('user_unblocked', 'Foydalanuvchi blokdan ochildi'), ('book_added', "Kitob qo'shildi"), ('book_updated', 'Kitob yangilandi'), ('book_deleted', "Kitob o'chirildi"), ('author_added', "Muallif qo'shildi"), ('author_updated', 'Muallif yangilandi'), ('author_deleted', "Muallif o'chirildi"), ('publisher_added', "Nashriyot qo'shildi"), ('publisher_updated', 'Nashriyot yangilandi'), ('publisher_deleted', "Nashriyot o'chirildi"), ('category_added', "Kategoriya qo'shildi"), ('category_updated', 'Kategoriya yangilandi'), ('category_deleted', "Kategoriya o'chirildi"), ('book_copy_added', "Kitob nusxasi qo'shildi"), ('book_copy_updated', 'Kitob nusxasi yangilandi'), ('book_copy_deleted', "Kitob nusxasi o'chirildi"), ('loan_requested', "Ijara so'rovi yaratildi"), ('loan_approved', "Ijara so'rovi tasdiqlandi"), ('loan_returned', 'Kitob qaytarildi'), ('fine_added', 'Jarima yozildi'), ('fine_paid', "Jarima to'landi"), ('waitlist_created', 'Navbat yaratildi'), ('waitlist_status_changed', "Navbat holati o'zgardi")], max_length=25, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='systemlogs',
            name='target_type',
            field=models.CharField(blank=True, choices=[('user', 'Foydalanuvchi'), ('book', 'Kitob'), ('author', 'Muallif'), ('publisher', 'Nashriyot'), ('category', 'Kategoriya'), ('book_copy', 'Kitob nusxasi'), ('loan', 'Ijara'), ('fine', 'Jarima'), ('waitlist', 'Navbat'), ('notification', 'Xabar')], max_length=20, null=True, verbose_name="Ob'ekt turi"),
        ),
    ]
