# Generated by Django 6.0.5 on 2026-05-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_fines_options_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loans',
            options={'ordering': ['created_at'], 'verbose_name': 'Ijara', 'verbose_name_plural': 'Ijaralar'},
        ),
        migrations.AlterModelOptions(
            name='waitlists',
            options={'ordering': ['created_at'], 'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
    ]
