# Generated by Django 6.0.5 on 2026-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loans_options_alter_waitlists_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlogs',
            name='action',
            field=models.CharField(choices=[('user_registered', "Foydalanuvchi ro'yxatdan o'tdi"), ('user_updated', 'Foydalanuvchi yangilandi'), ('user_blocked', 'Foydalanuvchi bloklandi'), ('user_unblocked', 'Foydalanuvchi blokdan ochildi'), ('book_added', "Kitob qo'shildi"), ('book_updated', 'Kitob yangilandi'), ('book_deleted', "Kitob o'chirildi"), ('author_added', "Muallif qo'shildi"), ('author_updated', 'Muallif yangilandi'), ('author_deleted', "Muallif o'chirildi"), ('publisher_added', "Nashriyot qo'shildi"), ('publisher_updated', 'Nashriyot yangilandi'), ('publisher_deleted', "Nashriyot o'chirildi"), ('category_added', "Kategoriya qo'shildi"), ('category_updated', 'Kategoriya yangilandi'), ('category_deleted', "Kategoriya o'chirildi"), ('book_copy_added', "Kitob nusxasi qo'shildi"), ('book_copy_updated', 'Kitob nusxasi yangilandi'), ('book_copy_deleted', "Kitob nusxasi o'chirildi"), ('loan_requested', "Ijara so'rovi yaratildi"), ('loan_approved', "Ijara so'rovi tasdiqlandi"), ('loan_returned', 'Kitob qaytarildi'), ('fine_added', 'Jarima yozildi'), ('fine_paid', "Jarima to'landi"), ('waitlist_created', 'Navbat yaratildi'), ('waitlist_status_changed', "Navbat holati o'zgardi")], max_length=50, verbose_name='Amal'),
        ),
    ]
